### ISSUE TITLE
Simple example of using a Google Sheet as a data source

### ISSUE THREAD

**Issue by andyburnett** [FTCOpenAlliance/.github#1]
@hamidh-2k8 we were talking about how to get the data from a Google form into a static page. There are several ways we could do it, but I think using Appscript is probably the easiest. This function shows how to return a JSON object as the result of a GET request to a spreadsheet url. It is actually quite fast. 

I would imagine we could use a table web component like this one: https://m2.material.io/components/data-tables/web#using-data-tables to display the data, and handle the data population via parsing the JSON object. 

function doGet(response) {
  
  var ss = SpreadsheetApp.openById('1lo8MPuyQUrRwVO6cwmTNmYcbPtk3U7Ko9CniMjtfL4Y');
  var sheet =  ss.setActiveSheet(ss.getSheets()[0]);
  var range = sheet.getRange("A2:A2");
 var cell = range.getCell(1, 1);
  var balance = cell.getValue();
 let json = {'balance':balance};
 let JSONString = JSON.stringify(json);
 let JSONOutput = ContentService.createTextOutput(JSONString);
 JSONOutput.setMimeType(ContentService.MimeType.JSON); 
return JSONOutput;
}

**Comment by hamidh-2k8** [comment]
This is definitely interesting, and I'll assume we just store the spreadsheet in our Electric Mayhem google drive. Another thing I was looking into was [Tripetto](https://tripetto.app/), which is like a free version of the popular form software TypeForm. I want to use Tripetto because it has a way better frontend experience and less branding compared to Google Forms, which is important to me as I think giving teams a polished and professional experience from the beginning will help convince them to join. Tripetto exports its data as CSV, meaning we can make a custom local script for converting into JSON, use a third-party service to convert it, or import it into google sheets and use an Apps Script to do it. These Tripetto forms can also be embedded into websites easily with their provided JS scripts. [Here's an example](https://tripetto.app/run/G50IZMV7V1) of a Tripetto form I made to recruit auditions for a film project (the image on the first page is broken, we were using Discord CDN to host it temporarily).

**Comment by andyburnett** [comment]
Tripetto looks very nice. I think we have several interesting options.

The big advantage of Google Forms/sheets is that - using Appscript - we would not have to do anything to the data. In other words, people would submit their data via the form, and we could then serve those data directly into the website. Furthermore, if people retained the link to their form submission, they would be able to update their data without us doing anything, e.g. if they changed their repo URL etc. However, the Google form is not as aesthetically pleasing as the alternatives.

If we gather the data via Tripetto it means that we will need to upload the CSV file to Github whenever the data change (but we don't think that will happen very often). Having a CSV file in the repo would mean that we could then use the Liquid templating language to generate the various pages that contain data. I have used Liquid on a few occasions and I have been very impressed with both its power and relative simplicity.

**Comment by hamidh-2k8** [comment]
I think we have slightly different ideas of how the data is ingested  Through your method, data would appear as soon as it was submitted through the form. I was thinking that all of the data would be made public on a set date, maybe a few days or a week after kickoff, meaning we would just do a single manual upload of the CSV to sheets and do the same Apps Script procedure from there. I don't think people would be making new build threads or repos very often, and on the off chance they happened to need something like a pit scouting stat changed, they could contact us directly.

I'm interested in Liquid, how does it generate these pages? Is it able to be integrated with web frameworks and/or plain HTML+CSS

**Comment by andyburnett** [comment]
Basically, 'yes'. Using the Google Form + Appscript approach would mean that we never touch the data, and it all becomes available, once we actually turn that connection on. Of course, it is up to us when we actually turn it on, and we could delay it until we are ready.  Not having to process the data is beneficial, but given that we are only inviting a small number of teams to start with, the benefit is small. So, processing the data by hand, uploading the data, and making changes if necessary is not a problem at all.

[Liquid](https://shopify.github.io/liquid/) is a powerful server side templating language. I have tended to use it to generate plain HTML+CSS, which I then manipulate using javascript frameworks. It might be work well in conjunction with something like Vue. However, given what we are trying to do, I suspect all we need is something simple like Material.io and a small about to JS.

Either way, the nice thing about Liquid is that it includes the ability to iterate over CSV data, and that is really useful for any pages we want to generate that contain tabular data etc.

Perhaps combining this with something like [Lunr](https://lunrjs.com) would give us everything we need to get started.

**Comment by hamidh-2k8** [comment]
These are some interesting projects, and they definitely seem like they could help out with the front-end data presentation. I think if we want to stick to the all-at-once release, then the forms can be handled by Tripetto, as the manual effort would be minimal and we can switch to an equally visually appealing in-house solution later. As for the actual website, we can start off with a basic site made with a simple web framework for the landing page, then integrate these solutions and/or others as we see fit for the data-driven pages.

Given that, I think we can put some of these ideas to the side for a bit (thankfully they're written down already) and make sure we have a foundation to integrate them on. Let's prioritize getting a repo up with a landing page first.

**Comment by andyburnett** [comment]
That sounds great. 

If we want to retain the option to use Liquid, and we plan on using GitHub pages, then it is probably worth setting up the site using GitHub's Jekyll system. It just makes it easier to run the Ruby build process at a later date.

**Comment by hamidh-2k8** [comment]
I'll look into that and other gh pages options and we'll try to get something set up today. Ill try to make a landing page prototype as well.

**Comment by hamidh-2k8** [comment]
@andyburnett as a sidenote, i'd like to keep these conversations to google chat threads. You should have access through aburnett@nicholsschool.org . Have you been able to see it?

**Comment by andyburnett** [comment]
I totally agree, but unfortunately, the school seems to have disabled my account. Perhaps they do that at the end of each year? Whatever the cause, it means I can’t access the chat thread. However, if you can add my Andy.burnett@knowinnovation.com account to the chat space, we can sidestep the problem

**Comment by hamidh-2k8** [comment]
I've made a new chat space with external members enabled and invited you. Closing this issue now.
